# -*- coding: utf-8 -*-
"""Capstone project BI .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jF0JubShCWFRZrle2qUbdforhKXxLd7u
"""

!pip install langchain-community langchain-text-splitters

import gradio as gr
import google.generativeai as genai
from langchain_community.document_loaders import TextLoader, PyPDFLoader, CSVLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import UnstructuredExcelLoader

"""Setting up LLM"""

import google.generativeai as genai
from getpass import getpass

GOOGLE_API_KEY = getpass("Enter your API key: ")

genai.configure(api_key=GOOGLE_API_KEY)

llm = genai.GenerativeModel("models/gemini-2.5-flash")

#response = model.generate_content("Explain how AI works in simple terms")

print(llm)

##AIzaSyCHH7MncYdV67uoV3GYCEc-ghnNVr0vOVk

"""Loading the PDF and split into tokens"""

pip install PyPDF

!pip install unstructured

!pip install msoffcrypto

Pdf1_reader = PyPDFLoader("AI business model innovation.pdf")
pdf2_reader = PyPDFLoader("BI approaches.pdf")
pdf3_reader = PyPDFLoader("timeseries.pdf")
pdf4_reader = PyPDFLoader("Walmarts sales data analysis.pdf")
pdf1_pages = Pdf1_reader.load_and_split()
pdf2_pages = pdf2_reader.load_and_split()
pdf3_pages = pdf3_reader.load_and_split()
pdf4_pages = pdf4_reader.load_and_split()

print(len(pdf1_pages))
print(pdf1_pages[0])

csv_loader = CSVLoader("sales_data.csv")
csv_pages = csv_loader.load_and_split()

print(f"Number of pages/sheets loaded: {len(csv_pages)}")
if csv_pages:
    print("First page content (truncated):")
    print(str(csv_pages[0])[:500]) # Print first 500 characters of the first page content

""" Split the pages into chunks using langchain libraries"""

text_split = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=64)
docs1 = text_split.split_documents(pdf1_pages)
docs2 = text_split.split_documents(pdf2_pages)
docs3 = text_split.split_documents(pdf3_pages)
docs4 = text_split.split_documents(pdf4_pages)
print(len(docs1))
print(docs1[3])
print(len(docs2))
print(docs2[3])
print(len(docs3))
print(docs3[3])
print(len(docs4))
print(docs4[3])
print(len(csv_pages))
print(csv_pages[3])

"""Storing the embedded vectors into VectorStore"""

Model_name = "sentence-transformers/all-mpnet-base-v2"
hf_mod = HuggingFaceEmbeddings(model_name=Model_name)
text1= docs1[0].page_content
text_embedding1 = hf_mod.embed_documents([text1])
text2= docs2[0].page_content
text_embedding2 = hf_mod.embed_documents([text2])
text3= docs3[0].page_content
text_embedding3 = hf_mod.embed_documents([text3])
text4= docs4[0].page_content
text_embedding4 = hf_mod.embed_documents([text4])
csv_text= csv_pages[0].page_content
print(len(text_embedding1[0]))
print(len(text_embedding2[0]))
print(len(text_embedding3[0]))
print(len(text_embedding4[0]))
print(len(csv_text))

"""checking the embeded chunks

"""

embed_chunks1 = [hf_mod.embed_query(chunk.page_content) for chunk in docs1]
enbed_chunks2 = [hf_mod.embed_query(chunk.page_content) for chunk in docs2]
embed_chunks3 = [hf_mod.embed_query(chunk.page_content) for chunk in docs3]
embed_chunks4 = [hf_mod.embed_query(chunk.page_content) for chunk in docs4]

import pandas as pd
df = pd.DataFrame(embed_chunks1)
df



pip install faiss-cpu

"""# Create a FAISS vector store and create a retriever

"""

vector_store = FAISS.from_documents(docs1,hf_mod)

all_docs = docs1 + docs2 + docs3 + docs4 + csv_pages
overall_vector_store = FAISS.from_documents(all_docs, hf_mod)
retriever = overall_vector_store.as_retriever()

from langchain_core.prompts import ChatPromptTemplate

template="""You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Use one sentence and keep the answer concise.
Question: {question}
Context: {context}
Answer:
"""

prompt=ChatPromptTemplate.from_template(template)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

output_parser=StrOutputParser()

!pip install langchain-google-genai
import gradio as gr
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI

# Initialize the Gemini model for LangChain
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GOOGLE_API_KEY)

# Defining RAG
rag_chain = (
    {"context": retriever | RunnablePassthrough(), "question": RunnablePassthrough()}
    | prompt
    | llm
    | output_parser
)

def greet(Ask_here):
   print("Processing question:", Ask_here)
    # Invoke the RAG chain and return the resulting string
   response_content = rag_chain.invoke(Ask_here)
   return response_content

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True)

from langchain_core.chat_history import BaseChatMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

store = {}

def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

"""Now, let's create a new RAG chain that incorporates the memory."""

rag_chain_with_history = RunnableWithMessageHistory(
    rag_chain,
    get_session_history,
    input_messages_key="question",
    history_messages_key="chat_history",
    output_messages_key="answer",
)

"""Finally, let's update the Gradio interface to use the new chain with memory."""

def greet(Ask_here, chat_history): # chat_history will be managed by Gradio
    session_id = "your_session_id"  # In a real app, this would be dynamic per user
    config = {"configurable": {"session_id": session_id}}
    response_content = rag_chain_with_history.invoke(
        {"question": Ask_here, "chat_history": chat_history},
        config=config
    )
    return response_content

# Gradio interface to include chat history

    def greet(Ask_here):
      print("Processing question:", Ask_here)
    # Invoke the RAG chain and return the resulting string
      response_content = rag_chain.invoke(Ask_here)
    return response_content


    def user_message(user_message, history):
        return "", history + [[user_message, None]]

    def bot_response(history):
        user_question = history[-1][0]
        session_id = "your_session_id" # Consistent session ID for the demo
        config = {"configurable": {"session_id": session_id}}
        response = rag_chain_with_history.invoke(
            {"question": user_question},
            config=config
        )
        history[-1][1] = response
        return history

    msg.submit(user_message, [msg, chatbot], [msg, chatbot], queue=False).then(
        bot_response, chatbot, chatbot
    )
    clear.click(lambda: None, None, chatbot, queue=False)
    #
demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True)

sample_question = "summary of  sales_data.csv'"
response = rag_chain.invoke(sample_question)
print(response)

import pandas as pd
df = pd.read_csv('sales_data.csv')
df

df.

"""### Sales Over Time Analysis

To understand the sales trend, we'll convert the 'Date' column to datetime objects, group the `df` DataFrame by date, and sum the 'Sales' to get daily total sales. Then, we'll visualize this with a line plot.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'])

# Aggregate daily sales
daily_sales = df.groupby('Date')['Sales'].sum().reset_index()

# Extract year for categorization in boxplot
daily_sales['Year'] = daily_sales['Date'].dt.year

# Plot sales distribution by year using boxplot
plt.figure(figsize=(12, 6))
sns.boxplot(x='Year', y='Sales', data=daily_sales)
plt.title('Distribution of Daily Sales by Year')
plt.xlabel('Year')
plt.ylabel('Total Daily Sales')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Plot overall sales trend over time with a line plot
plt.figure(figsize=(15, 7))
sns.lineplot(x='Date', y='Sales', data=daily_sales)
plt.title('Overall Daily Sales Trend Over Time')
plt.xlabel('Date')
plt.ylabel('Total Daily Sales')
plt.grid(True)
plt.tight_layout()
plt.show()

import gradio as gr
import matplotlib.pyplot as plt
import seaborn as sns

def plot_yearly_sales_boxplot():
    # Make sure daily_sales and its 'Year' column are available (assuming they are from previous cells)
    # If not, you might need to re-run the data processing steps within this function or pass them as arguments.

    # Plot sales distribution by year using boxplot
    plt.figure(figsize=(12, 6))
    sns.boxplot(x='Year', y='Sales', data=daily_sales)
    plt.title('Distribution of Daily Sales by Year')
    plt.xlabel('Year')
    plt.ylabel('Total Daily Sales')
    plt.grid(True)
    return plt.gcf() # Return the current figure object

# Create the Gradio interface
iface_boxplot = gr.Interface(
    fn=plot_yearly_sales_boxplot,
    inputs=[],
    outputs=gr.Plot(), # Use gr.Plot to display matplotlib figures
    title='Daily Sales Distribution by Year'
)

# Launch the Gradio interface
iface_boxplot.launch(share=True)